# Generated by Django 2.2.19 on 2022-05-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название позиции', max_length=30000, verbose_name='Название позиции')),
                ('purchase_price', models.PositiveIntegerField(help_text='Укажите закупочную цену', verbose_name='Закупочная цена')),
                ('selling_price', models.PositiveIntegerField(default=0, help_text='Укажите цену продажи', verbose_name='Цена продажи')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('sell_date', models.DateTimeField(default=None, verbose_name='Дата продажи')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to=settings.AUTH_USER_MODEL, verbose_name='Закупщик')),
                ('seller', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ('-add_date', 'name'),
            },
        ),
    ]
