# Generated by Django 2.2.19 on 2022-05-30 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sell_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
