# Generated by Django 2.2.19 on 2022-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220530_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий', max_length=30000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(help_text='Введите название позиции', max_length=500, verbose_name='Название позиции'),
        ),
    ]
