# Generated by Django 2.2.19 on 2022-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение позиции', upload_to='', verbose_name='Изображение'),
        ),
    ]
