# Generated by Django 2.2.19 on 2022-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20220531_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, help_text='Введите комментарий', max_length=10000, null=True, verbose_name='Комментарий'),
        ),
    ]
