# Generated by Django 2.2.19 on 2022-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20220531_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Введите название позиции', max_length=500, verbose_name='Название позиции'),
        ),
    ]
