# Generated by Django 2.2.19 on 2022-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20220601_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
