# Generated by Django 2.2.19 on 2022-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20220601_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='buyer',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_date',
            field=models.DateField(blank=True, help_text='Укажите дату продажи', null=True, verbose_name='Дата продажи'),
        ),
    ]
