# Generated by Django 2.2.19 on 2022-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20220601_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Отметка о продаже'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.PositiveIntegerField(default=0, help_text='Укажите цену продажи', verbose_name='Цена продажи'),
        ),
    ]
