# Generated by Django 2.2.19 on 2022-06-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20220601_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='selling_price',
            new_name='sell_price',
        ),
    ]
