# Generated by Django 2.2.19 on 2022-06-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0015_auto_20220601_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sell_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.AddField(
            model_name='item',
            name='earnings',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Укажите купленное количество', verbose_name='Купленное количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_unit_price',
            field=models.PositiveIntegerField(default=0, help_text='Укажите закупочную цену за 1 шт.', verbose_name='Закупочная цена за 1 шт.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Проданное количество'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField(help_text='Укажите дату продажи', verbose_name='Дата продажи')),
                ('sell_unit_price', models.PositiveIntegerField(help_text='Укажите цену продажи за 1 шт.', verbose_name='Цена продажи за 1 шт.')),
                ('count', models.PositiveIntegerField(help_text='Укажите проданное количество', verbose_name='Проданное количество')),
                ('comment', models.TextField(blank=True, help_text='Необязательный комментарий', max_length=10000, null=True, verbose_name='Комментарий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_items', to='items.Item', verbose_name='Проданные позиции')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Проданная позиция',
                'verbose_name_plural': 'Проданные позиции',
                'ordering': ('-sell_date', 'item'),
            },
        ),
    ]
