# Generated by Django 2.2.19 on 2022-06-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_auto_20220602_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='buyer',
        ),
    ]
