# Generated by Django 2.2.19 on 2022-06-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20220602_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchase_count',
            new_name='count',
        ),
    ]
