# Generated by Django 2.2.19 on 2022-06-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('-sell_date', 'item_id'), 'verbose_name': 'История продаж', 'verbose_name_plural': 'История продаж'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-add_date', 'name', 'count'), 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
