# Generated by Django 2.2.19 on 2022-06-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20220615_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-count', '-add_date', 'name'), 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
